### ISSUE TITLE
SKIP_TOKENS at the end of a number

### ISSUE THREAD

**Issue by noviluni** [scrapinghub/number-parser#30]
Hi @arnavkapoor!

I was trying the package, and I found a side effect when trying to parse sentences in Spanish.

```python
>>> parse('Avisté tres y luego nos fuimos.', language='es')
'Avisté 3 luego nos fuimos.'
```

this would be approx. equivalent to:

```python
>>> parse('I sighted three and then we left')
'I sighted 3 then we left'
```

As you can see, the "y" (or "and") disappears, but it should remain. We should probably avoid taking the "SKIP_TOKENS" when they are at the end of the number. What do you think?

**Comment by arnavkapoor** [comment]
Thanks @noviluni , yes is definitely a missed edge case will fix it.
