### ISSUE TITLE
The links at the end of README.rst file are redirecting

### ISSUE THREAD

**Issue by Manish-210** [scrapinghub/number-parser#51]
The following links:
    Source code: https://github.com/arnavkapoor/number-parser
    Issue tracker: https://github.com/arnavkapoor/number-parser/issues
are redirecting to:
    https://github.com/scrapinghub/number-parser
    https://github.com/scrapinghub/number-parser/issues 
I was thinking to change it to the direct these links.

**Comment by noviluni** [comment]
Hi @Manish-210! Thanks for the comment. 

I also think it's a good idea to change them, feel free to submit a Pull Request :)

**Comment by noviluni** [comment]
closed by: https://github.com/scrapinghub/number-parser/pull/52
